### ISSUE TITLE
Warning within recoveryRatePositive(): `Error in if: argument is of length zero`

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#105]
@bryce-carson 

I pulled the latest code and ran an SIR model simulation. For a split second there was an error and then it disappeared. The RStudio console had the following error messages.

```
Warning: Error in if: argument is of length zero
  137: <reactive:recoveryRatePositive> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#252]
  121: recoveryRatePositive
  114: <reactive:renderModel> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#132]
   98: renderModel
   97: renderUI
   96: func
   83: renderFunc
   82: output$outputPanel
    1: shiny::runApp
Warning: Error in if: argument is of length zero
  123: <Anonymous>
  122: stop
  121: recoveryRatePositive
  114: <reactive:renderModel> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#132]
   98: renderModel
   97: renderUI
   96: func
   83: renderFunc
   82: output$outputPanel
    1: shiny::runApp
```

**Comment by bryce-carson** [comment]
> @bryce-carson 
> 
> I pulled the latest code and ran an SIR model simulation. For a split second there was an error and then it disappeared. The RStudio console had the following error messages.
> 
> ```
> Warning: Error in if: argument is of length zero
>   137: <reactive:recoveryRatePositive> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#252]
>   121: recoveryRatePositive
>   114: <reactive:renderModel> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#132]
>    98: renderModel
>    97: renderUI
>    96: func
>    83: renderFunc
>    82: output$outputPanel
>     1: shiny::runApp
> Warning: Error in if: argument is of length zero
>   123: <Anonymous>
>   122: stop
>   121: recoveryRatePositive
>   114: <reactive:renderModel> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#132]
>    98: renderModel
>    97: renderUI
>    96: func
>    83: renderFunc
>    82: output$outputPanel
>     1: shiny::runApp
> ```

Thanks. I probably missed a `req`. It'll be an easy fix. Things like this are related to the reactive value propagation. For a small amount of time they're unavailable, but then they become available.

I'm going to do some professional development (just reading on the job) to get the more advanced Shiny concepts under my belt. It'll help smooth out errors like this further.

For now, I'll ensure the used reactive values are `req`uired and `need`ed, so friendly messages and wait timers ⏲️ appear instead of "error" when the real issue is lack of availability and waiting for some "engine oil" to circulate after powering things on.

**Comment by bryce-carson** [comment]
I believe this should be fixed now, but if it reappears please reopen it.
