### ISSUE TITLE
Change the top ribbon from White to Blue

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#112]
@Toby-exe  and @kle6951 

Currently we have

<img width="1276" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/ba3f550b-e52d-401a-abaa-a0738aa2f22f">

I would like this to have a blue ribbon like this (https://github.com/ashokkrish/spatialEpisim)

<img width="967" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/b68a93b2-0646-4bfb-9399-a12807a71783">

or like this (https://github.com/ashokkrish/CougarStats)

<img width="866" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/ad1256b4-e8d9-4407-afe3-3d7440ff71de">

**Comment by kle6951** [comment]
@ashokkrish  I have changed the color of the top ribbon. However, the GitHub icon is a mismatch with the overall interface design. Since the icon is a built-in SVG, I can't change the color of it. Would you like to remove the icon or do you want to keep it? If you want to keep the icon, I will find a way to change the color. 
<img width="1439" alt="Screenshot 2024-06-07 at 5 35 52 PM" src="https://github.com/ashokkrish/episim/assets/76984067/da124eb6-3421-4f5b-8ffe-739dad027fea">

**Comment by kle6951** [comment]
_**Here are the changes that I made:**_
1. Updated the color of all elements and the top ribbon of the app 
2. Removed the GitHub icon in the title bar
3. Moved the GitHub reference link into the `Links` button and placed it above the institution link as requested
