### ISSUE TITLE
Error when I press Run App

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#145]
```
Error in box::use(reactcharteditor/R/plotly_editor) : 
  unable to load module “reactcharteditor/R/plotly_editor”; not found in 
“C:/Users/ashok/Desktop/spatialEpisim2022/episim/R”, 
“C:/Users/ashok/AppData/Local/R/win-library/4.4/box/mod”, 
“C:/Users/ashok/Desktop/spatialEpisim2022/episim”
```

@Toby-exe or @bryce-carson Can you take a look at this error at your earliest convenience?

**Comment by bryce-carson** [comment]
Make sure you synchronize/populate the submodule!

**Comment by bryce-carson** [comment]
You should be able to change into that directory. Then it will be ready for use.

**Comment by ashokkrish** [comment]
> Make sure you synchronize/populate the submodule!

Sorry, how do I do that? Please help me with this.

**Comment by bryce-carson** [comment]
It is best to Google the git documentation or a blog guide to get some
instructions. I don't know off by hand, and I use a special interface to
Git (in Emacs) which handles most of it for me.

Regards,

Bryce.

**Comment by bryce-carson** [comment]
It is possible to have this not be a Git submodule as well.

It might be easier for you and others that way... rather, it would be.

Go to https://github.com/Toby-exe/react-chart-editoR and download the
latest version.

Overwrite the folder inside R. The name of the folder inside R must be
exactly the same when you overwrite it, so if the name changes (because the
repository has a slightly different name than the module/package) you must
rename the folder to exactly "reactcharteditor".

I'm going to do my best to NOT check my email the rest of the weekend. I
must focus on unwinding. 😀

Toby is familiar with the build step of this JavaScript library, so if
anything goes wrong he might be available to help you. It is the weekend,
however, and as far as I can tell everything is correct. It should all just
work if the dependencies are installed and any unforeseen error messages or
warnings are carefully understood.

Regards,

Bryce.

**Comment by bryce-carson** [comment]
Closing issue due to user error. @ashokkrish.

These instructions are valid, but please see and follow the instructions in the email I sent today instead.
