### ISSUE TITLE
Langauges used

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#146]
<img width="238" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/2daecad7-0c00-479d-afea-8c20a3e78910">

Since when did we go from using R 100% to 99.5% JavaScript?

Ever since libraries like `here` and `box` came into the fold the app has not properly run at all. Can we keep things simple for this simple R Shiny app please?

**Comment by bryce-carson** [comment]
@ashokkrish, it has nothing to do with the here library, and also nothing to do with the box library. Nothing at all.

This is an issue with GitHub, which has _misunderstood_ our project. They use an automated tool to look at our project source tree and they _guess_ what the language we use is. It guessed wrong.

The project does indeed work correctly, and it has run properly most of the time, actually. There have been issues, unfortunately, but some of them are due to user error.

[There is a way to force GitHub to properly recognize what languages are used,](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-languages) but I don't have the time for that right now. It's still a holiday. I'll get to it on Tuesday if you really want. It's not a relevant issue, though.

I _am curious_ as to why it suddenly changed, however. GitHub is weird, sometimes.
