### ISSUE TITLE
Flow diagrams

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#77]
I like where this is going with 
<img width="107" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/6020cab2-78aa-4cfc-b912-453412d27775">
<img width="440" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/7671929e-0f31-4b5e-b617-c3f2f1de5c83">
<img width="272" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/2ab3310a-1161-46fc-bda7-30b26040e171">
etc.

A couple of requests though

- The text inside the box to be uppercase letters (S, E, I.....)
- The arrow pointer be made a little small

Replace 
<img width="64" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/1fb723f6-7643-42b7-94b0-9832523bbbbf">
with something like 
<img width="38" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/27f40f66-5929-4c9b-a826-031d44eac452">

- The flow diagrams as a bigger image be place below the LaTeX equations on the mainpanel and the user can save this image locally.
- The transition pathways have the corresponding rates on top of the arrow (future work or optional).

**Comment by bryce-carson** [comment]
This would be a good issue to resole with JavaScript. The JavaScript library to use is [Mermaid](mermaid.js.org). The script can be included with [`htmltools::includeScript()`](https://rdrr.io/cran/htmltools/man/include.html).

# Suggested workflow
## Prior to inclusion of JavaScript
- [ ] Move the images to the model equations panel, updating the necessary sections throughout the entire codebase (you will need to review these files server.R, ui.R, global.R, and www/*.js). Ensure any code related to the current implementation is updated accordingly.

## Inclusion of JavaScript
- [ ] JavaScript and R can be used to generate the diagrams on the fly, rather than using images. It's worth looking into.
- [ ] Learn enough Mermaid to specify the exact positioning of edge labels (labels on connections between nodes). When I simply include a label like in the following example, it is centered on the arrow and that doesn't look good. Play with [the example here](https://mermaid.live/edit#pako:eNpVkMFqhEAMhl8l5NSCvoCHQlfbvWzZhe5NPQSNzrDOjIwZlkV9944rhTankP_7k_DP2LiWMcNucPdGkRe4FpWFWO9lrryexNBUQ5q-LUcWMM7yY4HDy9HBpNw4atu_7vxhgyCfTxvGIErb27pL-dN_trxAUZ5oFDfWf5Xr3S3wUeqLiuv_K8pzdH2WHWUdpQ15yMnXmKBhb0i38fV5M1Qoig1XmMW25Y7CIBVWdo0oBXHfD9tgJj5wgmFsSbjQ1Hsyv0NutTj_tafxDCVB70KvMB4eJl5_AN2EYRA).

### Possibilities
- [ ] Use `paste` with the correct arguments to simply paste together component symbols `c("S", "I", "R") |> paste(sep = "-->")`. Play with the arguments.

**Comment by bryce-carson** [comment]
@ashokkrish There is no time left for this project to do this, but here is an idea I had. This is a rough mockup. If implemented, the real thing would be cleaner and the comparment boxes would have the same relative sizing.

![Select a compartmental model](https://github.com/ashokkrish/episim/assets/51974245/895c7207-0cfb-4750-ba75-33b2e7a7b7cf)

**Comment by ashokkrish** [comment]
Ok, let's not worry about it. For now, let's get the letters inside the boxes capitalized and move on. Thanks.

**Comment by bryce-carson** [comment]
> Ok, let's not worry about it. For now, let's get the letters inside the boxes capitalized and move on. Thanks.

I meant that there was no time to implement my new idea. There is time to move the diagrams into the same tab panel as the $\LaTeX{}$ and offer a download button for the image.

**Comment by bryce-carson** [comment]
mermaid can be used [from R with the DiagrammeR package](https://rich-iannone.github.io/DiagrammeR/articles/graphviz-mermaid.html).

**Comment by bryce-carson** [comment]
I have fixed the capitalization issue and this issue will be closed in an incoming commit.

**Comment by bryce-carson** [comment]
Without much more investment of time in the styling of the graphic (really low priority), I can't restyle the arrow size or make the rate appear above the arrows.

It's possible for me to make the rate variables appear in the graphic atop the arrows, however, but this doesn't look good and is not readable.

This is something that can be changed at any time in the future, so I suggest we close the issue after fixing the capitalization since the capitalization has a semantic meaning.
