### ISSUE TITLE
SEIR error

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#94]
For an SEIR model I set Rate of recovery (σ) to be equal to 0 and clicked Run Simulation. The app crashed with this error

```
Warning: Error in <Anonymous>: exposed == 0 is not TRUE
  1: shiny::runApp
```

**Comment by bryce-carson** [comment]
Yes, this is an intentional error in the "exposuRe" package I am writing for you. The Shiny app should prevent users from encountering this, but it is a TODO right now.

Unless there is a modelling/scientific reason why a SEIR model should have a sigma = 0 (I don't understand why that would be) then this is fully intentional.

It is essentially a "you entered the wrong argument, buddy guy" error. It will make sense interactively for the package, but doesn't make sense for the Shiny app wrapping the "exposuRe" package/function.

I will write more validation, alongside the validation that ensures the compartments sum to N.

**Comment by bryce-carson** [comment]
@ashokkrish if you'd like to run an SEI model, with only those compartments, we can add the model type. Otherwise, requiring all relevant parameters be non-zero is sensible.
